// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnqdlmnrxyeltfqzrnlb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNucWRsbW5yeHllbHRmcXpybmxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzODM2MjAsImV4cCI6MjA2ODk1OTYyMH0.bjjKl4yVT0eFJ7GTn5PPU7apMdUDS_NZPpQUKf69ChU";
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);